# Generated by Django 5.1.12 on 2025-10-06 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RefugiLliure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200, verbose_name='Nom')),
                ('descripcio', models.TextField(verbose_name='Descripció')),
                ('tipus', models.CharField(choices=[('refugi', 'Refugi'), ('bivac', 'Bivac'), ('cabana', 'Cabana'), ('alberg', 'Alberg')], max_length=20, verbose_name='Tipus')),
                ('imatges', models.JSONField(blank=True, default=list, verbose_name='Imatges')),
                ('ubicacio', models.CharField(max_length=300, verbose_name='Ubicació')),
                ('regio', models.CharField(choices=[('pirineus', 'Pirineus'), ('central', 'Catalunya Central'), ('costa_brava', 'Costa Brava'), ('costa_daurada', 'Costa Daurada'), ('terres_ebre', "Terres de l'Ebre"), ('aran', "Val d'Aran")], max_length=20, verbose_name='Regió')),
                ('altitud', models.IntegerField(verbose_name='Altitud (m)')),
                ('capacitat', models.IntegerField(verbose_name='Capacitat')),
                ('estat', models.CharField(choices=[('obert', 'Obert'), ('tancat', 'Tancat'), ('manteniment', 'En manteniment'), ('renovacio', 'En renovació')], default='obert', max_length=20, verbose_name='Estat')),
                ('serveis', models.JSONField(blank=True, default=list, verbose_name='Serveis')),
                ('clau_necessaria', models.BooleanField(default=False, verbose_name='Clau necessària')),
                ('tancat', models.BooleanField(default=False, verbose_name='Tancat')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creat el')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='Modificat el')),
            ],
            options={
                'verbose_name': 'Refugi Lliure',
                'verbose_name_plural': 'Refugis Lliures',
                'ordering': ['nom'],
            },
        ),
    ]
