"""
Django settings for refugis_lliures project.

Generated by 'django-admin startproject' using Django 5.1.12.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

import os
from pathlib import Path
from decouple import config

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Detect environment and load appropriate .env file
if os.environ.get('RENDER') or os.environ.get('PRODUCTION'):
    # Production environment (Render or other production)
    env_file = BASE_DIR / 'env' / '.env.production'
else:
    # Development environment
    env_file = BASE_DIR / 'env' / '.env.development'

# Load environment variables from the appropriate file
if env_file.exists():
    from decouple import Config, RepositoryEnv
    config = Config(RepositoryEnv(str(env_file)))
else:
    # Fallback to default config if no env file is found
    from decouple import config


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# Use a test secret key during testing
SECRET_KEY = config('SECRET_KEY', default='test-secret-key-for-testing-only-not-secure')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = config('DEBUG', default=True, cast=bool)

ALLOWED_HOSTS = config('ALLOWED_HOSTS', default='*').split(',')


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'corsheaders',
    'drf_yasg',
    'django_crontab',
    'api',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
    #'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'api.middleware.FirebaseAuthenticationMiddleware',  # Firebase Auth Middleware
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'refugis_lliures.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'refugis_lliures.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'

# Whitenoise configuration for serving static files in production
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Django REST Framework settings
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'api.authentication.FirebaseAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.AllowAny',
    ],
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 10,
}

# CORS settings
CORS_ALLOW_ALL_ORIGINS = config('CORS_ALLOW_ALL_ORIGINS', default=True, cast=bool)
CORS_ALLOWED_ORIGINS = config('CORS_ALLOWED_ORIGINS', default='').split(',') if config('CORS_ALLOWED_ORIGINS', default='') else []

# Firebase/Firestore settings
GOOGLE_APPLICATION_CREDENTIALS = config('GOOGLE_APPLICATION_CREDENTIALS', default='env/firebase-service-account.json')
FIREBASE_SERVICE_ACCOUNT_KEY = config('FIREBASE_SERVICE_ACCOUNT_KEY', default=None)

# Security settings for production
SECURE_SSL_REDIRECT = config('SECURE_SSL_REDIRECT', default=False, cast=bool)
SESSION_COOKIE_SECURE = config('SESSION_COOKIE_SECURE', default=False, cast=bool)
CSRF_COOKIE_SECURE = config('CSRF_COOKIE_SECURE', default=False, cast=bool)

# Redis Cache Configuration

REDIS_URL = config('REDIS_URL', default='redis://localhost:6379/1')

CACHES = {
    'default': {
        'BACKEND': 'django_redis.cache.RedisCache',
        'LOCATION': REDIS_URL,
        'OPTIONS': {
            'CLIENT_CLASS': 'django_redis.client.DefaultClient',
            'SOCKET_CONNECT_TIMEOUT': 5,
            'SOCKET_TIMEOUT': 5,
            'CONNECTION_POOL_KWARGS': {
                'max_connections': 50,
                'retry_on_timeout': True
            },
            'COMPRESSOR': 'django_redis.compressors.zlib.ZlibCompressor',
        },
        'KEY_PREFIX': 'refugis',
        'TIMEOUT': 300,  # 5 minuts per defecte
    }
}

# Cache timeouts personalitzats
CACHE_TIMEOUTS = {
    'refugi_detail': config('CACHE_TIMEOUT_REFUGI_DETAIL', default=600, cast=int),  # 10 minuts
    'refugi_list': config('CACHE_TIMEOUT_REFUGI_LIST', default=300, cast=int),  # 5 minuts
    'refugi_search': config('CACHE_TIMEOUT_REFUGI_SEARCH', default=180, cast=int),  # 3 minuts
    'refugi_coords': config('CACHE_TIMEOUT_REFUGI_COORDS', default=36000, cast=int),  # 1 hora
    'user_detail': config('CACHE_TIMEOUT_USER_DETAIL', default=300, cast=int),  # 5 minuts
    'proposal_detail': config('CACHE_TIMEOUT_PROPOSAL_DETAIL', default=300, cast=int),  # 5 minuts
    'proposal_list': config('CACHE_TIMEOUT_PROPOSAL_LIST', default=180, cast=int),  # 3 minuts
}


# Logging configuration: enable INFO logs for cache and firestore access tracing
import logging

# Define custom levels so logs can show friendly level names for quick identification
# Numeric values chosen between standard levels (DEBUG=10, INFO=20, WARNING=30)
CACHE_LEVEL = 21
FIRESTORE_LEVEL = 22
DAO_LEVEL = 23

# Register the custom level names so they appear as 'CACHE', 'FIRESTORE', 'DAO'
logging.addLevelName(CACHE_LEVEL, 'CACHE')
logging.addLevelName(FIRESTORE_LEVEL, 'FIRESTORE')
logging.addLevelName(DAO_LEVEL, 'DAO')

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'standard': {
            'format': '%(asctime)s [%(levelname)s] %(name)s: %(message)s'
        },
    },
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
            'formatter': 'standard',
        },
    },
    'loggers': {
        'api.services.cache_service': {
            'handlers': ['console'],
            'level': CACHE_LEVEL,
            'propagate': False,
        },
        'api.services.firestore_service': {
            'handlers': ['console'],
            'level': FIRESTORE_LEVEL,
            'propagate': False,
        },
        'api.daos': {
            'handlers': ['console'],
            'level': DAO_LEVEL,
            'propagate': False,
        },
        # Fallback for whole api package
        'api': {
            'handlers': ['console'],
            'level': 'WARNING',
            'propagate': False,
        },
    }
}

# Swagger/OpenAPI settings
SWAGGER_SETTINGS = {
    'SECURITY_DEFINITIONS': {
        'Bearer': {
            'type': 'apiKey',
            'name': 'Authorization',
            'in': 'header',
            'description': 'Token JWT de Firebase. Format: Bearer <token>'
        }
    },
    'USE_SESSION_AUTH': False,
    'JSON_EDITOR': True,
    'SUPPORTED_SUBMIT_METHODS': ['get', 'post', 'put', 'delete', 'patch'],
}

# Django-crontab settings
CRONJOBS = [
    # Processa les visites d'ahir cada dia a les 3:00 AM (hora de Madrid)
    ('0 3 * * *', 'django.core.management.call_command', ['process_yesterday_visits'], {'verbosity': 1}),
]
